version: '3'
services:
    postgres:
        image: 'postgres:latest'
        environment:
          - POSTGRES_PASSWORD=postgres_password
    redis:
        image: 'redis:latest'
    nginx:
        depends_on:
            - api
            - client
        restart: 'always'
        build:
            dockerfile: 'Dockerfile.dev'
            context: './nginx'
        ports:
            - '4000:80'
    api:
        depends_on:
            - redis
            - postgres
        build:
            dockerfile: 'Dockerfile.dev'
            context: './api'
        volumes:
            - '/app/node_modules'
            - './api:/app'
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - PGUSER=postgres
            - PGHOST=postgres
            - PGDATABASE=postgres
            - PGPASSWORD=postgres_password
            - PGPORT=5432
    client:
        stdin_open: true
        build:
            dockerfile: 'Dockerfile.dev'
            context: './client'
        volumes:
            - '/app/node_modules'
            - './client:/app'
    worker:
        build:
            dockerfile: 'Dockerfile.dev'
            context: './worker'
        volumes:
            - '/app/node_modules'
            - './worker:/app'
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379